insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lynna Draper', '763 Johnson Avenue', '5/11/1956');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Taddeusz Bickerdicke', '8 Utah Drive', '1/27/1956');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Torrie Nitti', '4 Carey Parkway', '2/28/1979');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jennie Woodington', '782 Farmco Plaza', '12/9/1988');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gaspar Boothroyd', '5740 Main Center', '3/12/2019');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Freedman Habden', '6495 Eastlawn Way', '11/6/2008');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kristofor Pearce', '1 Sycamore Hill', '2/26/1991');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Antoine Bim', '72635 Goodland Lane', '5/6/2009');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dorolisa Kivelhan', '959 Bay Circle', '7/4/1977');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Timmie Gaddes', '235 Esch Park', '11/3/1965');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adriano Chess', '0 Westport Park', '9/5/1972');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Saudra Ordelt', '45 Esch Drive', '2/4/2013');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Deana Davydkov', '6916 Golf View Way', '5/10/2011');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lefty Keyte', '39 Express Street', '11/5/1974');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maurene Ramel', '97014 Caliangt Park', '2/27/2005');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marcella Peniman', '0062 Anthes Junction', '1/11/1994');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Binky Tandey', '1 Marquette Place', '8/6/1989');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Trefor Greensted', '1 Stoughton Pass', '4/30/1996');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Augusta Horwell', '6 Stoughton Park', '4/6/1940');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kincaid Judkin', '50448 Shopko Terrace', '3/28/2014');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carmela Cotelard', '13546 Dixon Drive', '11/17/1972');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('La verne O''Lehane', '9 Old Shore Avenue', '3/10/1988');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Neville Venables', '058 Hayes Hill', '3/20/1951');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hall Dealtry', '35 Sullivan Hill', '1/25/1954');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Loise Reddan', '0479 Saint Paul Lane', '3/16/1945');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anallese Canfield', '189 Dottie Lane', '2/19/1964');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Merwyn Doumerque', '2 Parkside Place', '10/2/2002');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Burt Nowland', '79 Crest Line Hill', '11/22/1952');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lanie Westmacott', '23 Oneill Parkway', '3/16/1992');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('April Carlos', '898 Derek Drive', '4/14/2010');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Devi Binyon', '7 Meadow Ridge Avenue', '9/23/1984');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kerrin Scathard', '83629 Rutledge Trail', '10/14/1959');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Paulina Slesser', '3 Hintze Junction', '3/9/1951');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gare Ferreira', '1210 Maple Crossing', '8/6/2004');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rahel Yakovitch', '5887 Mesta Park', '5/10/1952');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rock Bruntjen', '5341 Aberg Park', '4/20/1968');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garland Nicholls', '13 Hazelcrest Drive', '6/16/1988');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Orelee Sighart', '534 Monument Place', '9/18/2006');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Katina Woolner', '03 Village Green Street', '6/27/1991');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andrew Denidge', '0 Moulton Plaza', '4/19/2001');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shelley Champagne', '97 Blue Bill Park Trail', '10/9/1947');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nicol Bodesson', '2121 Shelley Plaza', '11/13/2019');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kasper Usherwood', '3 Corben Plaza', '4/22/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adolphe Hylden', '6257 Schurz Way', '2/17/1969');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christabel Goslin', '98 Butterfield Court', '10/27/2001');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gisela Tague', '33673 Mccormick Lane', '12/3/1958');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ferdy Oluwatoyin', '31 Orin Lane', '11/4/2020');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brand Grattage', '6 Bluejay Circle', '9/15/2005');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Davita Manketell', '8036 Surrey Terrace', '1/12/1948');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sidney Strongitharm', '055 Waywood Trail', '1/26/1971');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kale Paulat', '70097 Lerdahl Park', '6/10/2012');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gaspard Olohan', '7116 Roth Plaza', '4/15/1969');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Trevor Ricardo', '0 Bashford Terrace', '9/21/1966');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Amargo Sanger', '16040 Randy Alley', '6/28/2014');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Margery Pinckstone', '4373 Toban Place', '7/26/1992');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danie Wallhead', '2058 Waxwing Pass', '2/4/1966');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Denyse Schistl', '4567 Brickson Park Plaza', '10/29/2003');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Orren Connal', '1646 Gateway Pass', '10/21/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Debby Daud', '19447 Redwing Point', '2/9/1999');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gail Gremane', '54 Moulton Lane', '1/20/1950');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rooney Mattingley', '168 Utah Point', '2/25/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brita Slym', '373 Rockefeller Avenue', '11/9/2003');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gerhardt Loudyan', '405 Duke Lane', '3/21/1944');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emlynn Robrose', '5439 Transport Circle', '6/6/1957');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clarette Tabord', '00 Manley Junction', '2/20/1959');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Agathe Pietrasik', '8 Maple Wood Lane', '1/21/1947');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Faye Pobjoy', '38 Village Green Park', '10/3/1999');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sherline Kolinsky', '42575 Beilfuss Place', '4/10/2004');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alvin Mackness', '10 Lakeland Court', '12/17/1983');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Barde Hulburd', '4 Chinook Drive', '3/4/1985');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leigh Holleran', '5636 Welch Court', '8/9/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rockey Bulbeck', '59 School Circle', '9/14/1990');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Averell Gillions', '6 Kings Parkway', '4/16/1975');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Horten Talbot', '18 Erie Crossing', '9/12/1953');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hayyim Blaik', '74 Loeprich Avenue', '4/27/2014');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Langsdon McVee', '06 Mcbride Street', '3/17/1976');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maggy De Cruz', '2059 Ridgeway Parkway', '5/28/1944');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shelia Dwelley', '627 Monument Road', '12/23/1947');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeffry Pinshon', '0566 Becker Terrace', '8/23/2009');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Baxter Simonitto', '98 Grasskamp Crossing', '11/25/1989');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Olympe Dawney', '958 Iowa Center', '1/3/1941');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gideon Alpe', '37497 Bay Drive', '4/28/1979');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garvy Newvell', '7 Mesta Street', '10/25/1996');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cletus Sesons', '057 Longview Alley', '9/29/2002');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Woodrow Passman', '87655 Morning Pass', '1/21/2000');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dennet Munnery', '3 Maple Hill', '11/14/1953');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fayette Sextie', '78743 Oak Way', '5/4/1943');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christan McKimmey', '71 Straubel Terrace', '10/4/1994');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harli Loud', '24602 Crownhardt Place', '5/16/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Holly Iacomettii', '87 Welch Road', '8/31/1982');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thom Boscott', '132 Maywood Hill', '11/19/2020');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Daryl Balffye', '04501 Wayridge Center', '11/15/1959');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giusto Gillis', '323 Basil Avenue', '7/4/1999');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Olivie Lande', '61 Onsgard Terrace', '11/13/1978');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alene Streatley', '35525 Esch Way', '1/5/1959');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tadio Penrose', '45601 Continental Alley', '3/5/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Estell Abarough', '6671 Dakota Way', '7/31/1973');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Miguel Monier', '4862 Brown Center', '11/8/2007');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Byron Tainton', '32410 Namekagon Junction', '1/11/2012');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sidney Heibl', '30202 Hoepker Place', '10/16/1941');
