insert into tren (modelo, capacidad) values ('Corvette', 78);
insert into tren (modelo, capacidad) values ('Savana 3500', 44);
insert into tren (modelo, capacidad) values ('Metro', 2);
insert into tren (modelo, capacidad) values ('88', 6);
insert into tren (modelo, capacidad) values ('Forester', 46);
insert into tren (modelo, capacidad) values ('Explorer', 39);
insert into tren (modelo, capacidad) values ('Explorer', 100);
insert into tren (modelo, capacidad) values ('Integra', 20);
insert into tren (modelo, capacidad) values ('Corolla', 22);
insert into tren (modelo, capacidad) values ('Monaro', 96);
insert into tren (modelo, capacidad) values ('Expedition EL', 33);
insert into tren (modelo, capacidad) values ('H2', 43);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 9);
insert into tren (modelo, capacidad) values ('XJ Series', 36);
insert into tren (modelo, capacidad) values ('Montana', 27);
insert into tren (modelo, capacidad) values ('GTO', 48);
insert into tren (modelo, capacidad) values ('Silhouette', 84);
insert into tren (modelo, capacidad) values ('Continental', 50);
insert into tren (modelo, capacidad) values ('LR4', 56);
insert into tren (modelo, capacidad) values ('W201', 1);
insert into tren (modelo, capacidad) values ('Metro', 3);
insert into tren (modelo, capacidad) values ('Esteem', 42);
insert into tren (modelo, capacidad) values ('Phaeton', 13);
insert into tren (modelo, capacidad) values ('GS', 36);
insert into tren (modelo, capacidad) values ('B-Series', 6);
insert into tren (modelo, capacidad) values ('Mighty Max', 94);
insert into tren (modelo, capacidad) values ('F250', 96);
insert into tren (modelo, capacidad) values ('Brat', 63);
insert into tren (modelo, capacidad) values ('Odyssey', 43);
insert into tren (modelo, capacidad) values ('Impreza', 42);
insert into tren (modelo, capacidad) values ('Frontier', 41);
insert into tren (modelo, capacidad) values ('Blazer', 34);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 47);
insert into tren (modelo, capacidad) values ('Cavalier', 35);
insert into tren (modelo, capacidad) values ('Lancer', 66);
insert into tren (modelo, capacidad) values ('RL', 36);
insert into tren (modelo, capacidad) values ('Ghost', 55);
insert into tren (modelo, capacidad) values ('G35', 55);
insert into tren (modelo, capacidad) values ('XLR', 68);
insert into tren (modelo, capacidad) values ('Eclipse', 53);
insert into tren (modelo, capacidad) values ('Sierra 2500', 8);
insert into tren (modelo, capacidad) values ('MX-3', 97);
insert into tren (modelo, capacidad) values ('STS', 84);
insert into tren (modelo, capacidad) values ('CR-Z', 21);
insert into tren (modelo, capacidad) values ('300E', 99);
insert into tren (modelo, capacidad) values ('Sierra 1500', 30);
insert into tren (modelo, capacidad) values ('M3', 62);
insert into tren (modelo, capacidad) values ('Corvair 500', 90);
insert into tren (modelo, capacidad) values ('SLR McLaren', 78);
insert into tren (modelo, capacidad) values ('CR-V', 34);
insert into tren (modelo, capacidad) values ('Spectra', 76);
insert into tren (modelo, capacidad) values ('Cayenne', 86);
insert into tren (modelo, capacidad) values ('RX-8', 23);
insert into tren (modelo, capacidad) values ('Ridgeline', 99);
insert into tren (modelo, capacidad) values ('300ZX', 15);
insert into tren (modelo, capacidad) values ('Freestar', 20);
insert into tren (modelo, capacidad) values ('Pathfinder', 50);
insert into tren (modelo, capacidad) values ('Esperante', 58);
insert into tren (modelo, capacidad) values ('Previa', 37);
insert into tren (modelo, capacidad) values ('Fairlane', 21);
insert into tren (modelo, capacidad) values ('626', 78);
insert into tren (modelo, capacidad) values ('Cayenne', 32);
insert into tren (modelo, capacidad) values ('Integra', 42);
insert into tren (modelo, capacidad) values ('Silverado 2500', 10);
insert into tren (modelo, capacidad) values ('Vanquish S', 43);
insert into tren (modelo, capacidad) values ('Esteem', 93);
insert into tren (modelo, capacidad) values ('Wrangler', 14);
insert into tren (modelo, capacidad) values ('7 Series', 56);
insert into tren (modelo, capacidad) values ('Tiburon', 85);
insert into tren (modelo, capacidad) values ('Town Car', 72);
insert into tren (modelo, capacidad) values ('Monte Carlo', 14);
insert into tren (modelo, capacidad) values ('F250', 95);
insert into tren (modelo, capacidad) values ('SJ', 11);
insert into tren (modelo, capacidad) values ('QX', 21);
insert into tren (modelo, capacidad) values ('ES', 33);
insert into tren (modelo, capacidad) values ('SX4', 53);
insert into tren (modelo, capacidad) values ('Econoline E350', 73);
insert into tren (modelo, capacidad) values ('Golf', 69);
insert into tren (modelo, capacidad) values ('Firefly', 37);
insert into tren (modelo, capacidad) values ('Town & Country', 92);
insert into tren (modelo, capacidad) values ('Silverado 1500', 90);
insert into tren (modelo, capacidad) values ('Passat', 74);
insert into tren (modelo, capacidad) values ('Camry', 97);
insert into tren (modelo, capacidad) values ('V12 Vantage', 25);
insert into tren (modelo, capacidad) values ('xA', 28);
insert into tren (modelo, capacidad) values ('Avalon', 79);
insert into tren (modelo, capacidad) values ('I', 85);
insert into tren (modelo, capacidad) values ('TT', 28);
insert into tren (modelo, capacidad) values ('Ascender', 90);
insert into tren (modelo, capacidad) values ('Suburban 2500', 23);
insert into tren (modelo, capacidad) values ('CLK-Class', 60);
insert into tren (modelo, capacidad) values ('Grand Am', 24);
insert into tren (modelo, capacidad) values ('Sierra 2500', 43);
insert into tren (modelo, capacidad) values ('Concorde', 16);
insert into tren (modelo, capacidad) values ('H1', 21);
insert into tren (modelo, capacidad) values ('CLK-Class', 13);
insert into tren (modelo, capacidad) values ('Navigator', 93);
insert into tren (modelo, capacidad) values ('Vanquish S', 79);
insert into tren (modelo, capacidad) values ('Suburban 1500', 69);
insert into tren (modelo, capacidad) values ('Defender 90', 21);
